### ISSUE TITLE
控制台报错，当资源不存在

### ISSUE THREAD

**Issue by ArvoGuo** [NodeLab/qin#10]
```
/xxx.png
TypeError: Cannot use 'in' operator to search for 'result' in undefined
    at Object.module.exports [as handle] (/Users/Arvo/github/qin/routes/get.js:22:21)
    at next_layer (/Users/Arvo/github/qin/node_modules/express/lib/router/route.js:103:13)
    at Route.dispatch (/Users/Arvo/github/qin/node_modules/express/lib/router/route.js:107:5)
    at c (/Users/Arvo/github/qin/node_modules/express/lib/router/index.js:195:24)
    at Function.proto.process_params (/Users/Arvo/github/qin/node_modules/express/lib/router/index.js:251:12)
    at next (/Users/Arvo/github/qin/node_modules/express/lib/router/index.js:189:19)
    at next (/Users/Arvo/github/qin/node_modules/express/lib/router/index.js:166:38)
    at next (/Users/Arvo/github/qin/node_modules/express/lib/router/index.js:166:38)
    at Function.proto.handle (/Users/Arvo/github/qin/node_modules/express/lib/router/index.js:234:5)
    at Layer.router (/Users/Arvo/github/qin/node_modules/express/lib/router/index.js:23:12)

```
问题：当xxx图片不存在时 ，控制台报错
原因：路由通过 dir层，到达get层，get层过滤问题。

**Comment by elrrrrrrr** [comment]
Duplicate of #4
